# Generated by Django 4.2.1 on 2023-06-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Econoclima',
        ),
    ]
