# Generated by Django 4.2.1 on 2023-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_rename_empleado_econoclima'),
    ]

    operations = [
        migrations.AddField(
            model_name='econoclima',
            name='año',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='econoclima',
            name='perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Perdidas en Millones'),
        ),
    ]
