# Generated by Django 4.2.1 on 2023-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_econoclima_año_econoclima_perdidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='econoclima',
            old_name='año',
            new_name='agricultura_año',
        ),
        migrations.RenameField(
            model_name='econoclima',
            old_name='perdidas',
            new_name='agricultura_perdidas',
        ),
        migrations.AddField(
            model_name='econoclima',
            name='infraestructura_año',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='econoclima',
            name='infraestructura_perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Perdidas en Millones'),
        ),
        migrations.AddField(
            model_name='econoclima',
            name='salud_año',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='econoclima',
            name='salud_perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Perdidas en Millones'),
        ),
        migrations.AddField(
            model_name='econoclima',
            name='turismo_año',
            field=models.IntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='econoclima',
            name='turismo_perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Perdidas en Millones'),
        ),
    ]
