# Generated by Django 4.2.1 on 2023-06-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_rename_año_econoclima_agricultura_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='econoclima',
            name='agricultura_año',
            field=models.IntegerField(default='0', verbose_name='Agricultura año'),
        ),
        migrations.AlterField(
            model_name='econoclima',
            name='agricultura_perdidas',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Agricultura perdidas en Millones'),
        ),
        migrations.AlterField(
            model_name='econoclima',
            name='infraestructura_año',
            field=models.IntegerField(null=True, verbose_name='Infraestructura año'),
        ),
        migrations.AlterField(
            model_name='econoclima',
            name='infraestructura_perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Infraestructura perdidas en Millones'),
        ),
        migrations.AlterField(
            model_name='econoclima',
            name='salud_año',
            field=models.IntegerField(null=True, verbose_name='Salud año'),
        ),
        migrations.AlterField(
            model_name='econoclima',
            name='salud_perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Salud perdidas en Millones'),
        ),
        migrations.AlterField(
            model_name='econoclima',
            name='turismo_año',
            field=models.IntegerField(null=True, verbose_name='Turismo año'),
        ),
        migrations.AlterField(
            model_name='econoclima',
            name='turismo_perdidas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Turismo perdidas en Millones'),
        ),
    ]
